# NumPy Cheatsheet

In [2]:
import numpy as np

### Creating arrays

In [4]:
# Create an array of 10 zeros:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Create an array of 10 ones:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# Create an array of 10 specific numers::
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
# create an array from a python list:
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
# access the 3rd element of the array
a[2]

np.int64(4)

In [11]:
# assign a new value to the 3rd element
a[2]=10
a

array([ 1,  2, 10,  4,  5])

In [12]:
# create a range from 0-9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create a range from 3-9: (equivalent to python range(3,10))
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
# create an array between numbers with a certain number of steps 
np.linspace(0,1,5)  # 5 numbers between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Multidimensional arrays

In [16]:
# Create an array of 5 rows and 2 columns of zeros:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
# create an array from a python list of lists:
m = np.array([ [1,2,3], [4,5,6], [7,8,9] ])

In [20]:
# Access the element at the 2nd row and 3rd column
m[1,2]

np.int64(6)

In [21]:
# Access the first row:
m[0]

array([1, 2, 3])

In [23]:
# Assign a new row to the first row:
m[0] = [10,11,12]
m

array([[10, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
# Access the first column:
m[:,0]

array([10,  4,  7])

In [28]:
# assign a new column to the first column:
m[:,0] = [20,30,40]
m

array([[20, 11, 12],
       [30,  5,  6],
       [40,  8,  9]])

### Randomly Generated Arrays

In [ ]:
# Generate a 3x3 array of random numbers between 0 and 1 - new numbers with each run
# sample from a uniform distribution
np.random.rand(3,3) 

array([[0.00464665, 0.53330923, 0.99643781],
       [0.06969023, 0.75843377, 0.52317464],
       [0.93424341, 0.0246164 , 0.01179465]])

In [31]:
# set a seed for reproducibility
np.random.seed(42)
np.random.rand(3,3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [33]:
# Sample from a standard normal distribution (mean 0, std 1)
np.random.seed(42)
np.random.randn(3,3)

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [ ]:
# Create a 5x2 array of random numbers between 0 and 100
np.random.randint(low=0,high=100,size=(5,2))

array([[58, 41],
       [91, 59],
       [79, 14],
       [61, 61],
       [46, 61]])

### Element-wise operations

In [36]:
# Create an array with a range between 0 and 5
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
# Add 1 to each element - this wouldn't be possible with a python list
a + 1

array([1, 2, 3, 4, 5])

In [40]:
# multiply each element by 2
a * 2

array([0, 2, 4, 6, 8])

In [46]:
# chain operations
b = (a * 2 + 10)**2
b

array([100, 144, 196, 256, 324])

In [44]:
# Sum two arrays element-wise
a + b

array([100, 145, 198, 259, 328])

### Elementwise comparison operations

In [ ]:
# Check which elements in 'a' are greater than 3 - returns a boolean array
a > 3

array([False, False, False, False,  True])

In [49]:
#compare two arrays element-wise
a == b

array([False, False, False, False, False])

In [ ]:
# check which elements of a are greater than b at the same index
a[a>b]


array([], dtype=int64)

### Aggregations

In [ ]:
# return the smallest number in an array
a.min() 

np.int64(0)

In [ ]:
# return the largest number in an array
a.max() 

np.int64(4)

In [55]:
# return the sum of all numbers in an array
a.sum()

np.int64(10)

In [56]:
# return the average of all numbers in an array
a.mean()

np.float64(2.0)

In [ ]:
# return standard deviation
a.std()

np.float64(1.4142135623730951)