# Linear Algebra

In [2]:
import numpy as np

### Vector Operations

In [3]:
# Multiply vector by a scalar
a = np.array([1, 2, 3])
2 * a

array([2, 4, 6])

In [4]:
# Add two vectors - elementwise addition
a + a

array([2, 4, 6])

#### Vector-Vector Multiplication - Dot Product

In [20]:
u = np.array([1, 2])
v = np.array([3, 4])

np.sum(u * v)  # multiply elementwise and sum the results

np.int64(11)

In [24]:
def vectorvectormultiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result=0

    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [25]:
vectorvectormultiplication(u, v)

np.int64(11)

### Matrix-Vector Multiplication - multiply every row vector of M with column vector v

In [28]:
# create a 3x4 matrix
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]]) 
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
v=np.array([1, 0, 1, 0])

In [30]:
M.dot(v)  # multiply every row vector of M with column vector v

array([ 4, 12, 20])

In [31]:
def matrixvectormultiplication(M, v):
    assert M.shape[1] == v.shape[0]
    m = M.shape[0]
    n = M.shape[1]
    result = np.zeros(m)

    for i in range(m):
        for j in range(n):
            result[i] = result[i] + M[i, j] * v[j]
    return result

In [32]:
matrixvectormultiplication(M, v)

array([ 4., 12., 20.])

### Matrix-Matrix Multiplaction - multiply each row with each column, return a new matrix

In [34]:
# create a 4x2 matrix N to multiply with M (3x4)
N = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])
N

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
M.dot(N)  # multiply every row vector of M with every column vector of N, return a new matrix

array([[ 50,  60],
       [114, 140],
       [178, 220]])

In [36]:
def matrixmultiplication(M, N):
    assert M.shape[1] == N.shape[0]
    m = M.shape[0]
    n = M.shape[1]
    p = N.shape[1]
    result = np.zeros((m, p))

    for i in range(m):
        for j in range(p):
            for k in range(n):
                result[i, j] = result[i, j] + M[i, k] * N[k, j]
    return result

### Identity Matrix - Square Matrix with 1 on diagonal 
Any Matrix U * I = U - The number 1 of matrices

In [39]:
# get identity matrix with dimensions 3x3
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Matrix Inverse
A^-1 * A = I  
a transformed matrix that when multiplied with itself returns I - only works with square matrices

In [60]:
# create square matrix V 4x4 and random values
np.random.seed(1)
V = np.random.randint(low=0,high=100,size=(4,4))
V


array([[37, 12, 72,  9],
       [75,  5, 79, 64],
       [16,  1, 76, 71],
       [ 6, 25, 50, 20]])

In [61]:
V_inv = np.linalg.inv(V)  # calculate the inverse of V
V_inv

array([[-0.00210166,  0.01776882, -0.01520499, -0.00193677],
       [-0.02536976,  0.01340354, -0.02306887,  0.05041953],
       [ 0.02204271, -0.01251562,  0.01088551, -0.0085128 ],
       [-0.02276408,  0.00920398,  0.0061838 ,  0.00883861]])

In [62]:
V.dot(V_inv)  # should return identity matrix

array([[ 1.00000000e+00, -3.81639165e-17,  9.97465999e-17,
        -1.21430643e-17],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17,
         1.11022302e-16],
       [ 1.97758476e-16, -5.89805982e-17,  1.00000000e+00,
        -5.72458747e-17],
       [-1.38777878e-17,  1.38777878e-17,  3.81639165e-17,
         1.00000000e+00]])