# NumPy Cheatsheet

In [2]:
import numpy as np

### Creating arrays

In [4]:
# Create an array of 10 zeros:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Create an array of 10 ones:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# Create an array of 10 specific numers::
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
# create an array from a python list:
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
# access the 3rd element of the array
a[2]

np.int64(4)

In [11]:
# assign a new value to the 3rd element
a[2]=10
a

array([ 1,  2, 10,  4,  5])

In [12]:
# create a range from 0-9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create a range from 3-9: (equivalent to python range(3,10))
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
# create an array between numbers with a certain number of steps 
np.linspace(0,1,5)  # 5 numbers between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])